external/vulkancts/modules/vulkan/api/vktApiDeviceInitializationTests.cpp
The spec states that:
>If apiVersion is 0 the implementation **must** ignore it [...]
I added a test for that case.
It might seem a little silly, but currently the Vulkan [loader](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) form Khronos segfaults at [loader.h](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/1affe90f0ec7f9bccb6841a56a2a5b66861efe6a/loader/loader.h#L362) if you do set it to zero.
=> Added a test when apiVersion is 0

external/openglcts/modules/gl/gl4cPipelineStatisticsQueryTests.cpp
m_current_draw_call_type and m_current_primitive_type should not be
processed in PipelineStatisticsQueryTestFunctional1.
Otherwise we have reads from uninitialized fields.
=> Fix GL45-CTS.pipeline_statistics_query_tests_ARB.functional_default_qo_values

external/openglcts/modules/gl/gl4cShaderSubroutineTests.cpp
Fixes github issue #48.
Affects:
KHR-GL45.shader_subroutine.subroutines_with_separate_shader_objects
Components: OpenGL
=> Avoid accessing out-of-bounds input patch vertices

external/openglcts/modules/gl/gl4cEnhancedLayoutsTests.cpp
Affects:
KHR-GL45.enhanced_layouts.varying_structure_locations
Components: OpenGL
GitHub Issue: #53
=> Always apply flat qualifier to double inputs, same as int/uint

framework/platform/lnx/X11/tcuLnxX11GlxPlatform.cpp
The regular function pointers are filled in on load, but any additional
pointers, potentially from extensions, requested by tests would end up
with NULLs, triggering failures.
Affects:
KHR-GL45.transform_feedback.draw_xfb_instanced_test
KHR-GL45.transform_feedback.draw_xfb_stream_instanced_test
=> glx: add getProcAddress override

external/vulkancts/modules/vulkan/api/vktApiFeatureInfo.cpp
The VK_KHR_get_physical_device_properties2 extension is necessary to be able to run this test, this PR makes the deviceFeatures2 function more similar to the deviceProperties2 function.
=> Require extension for the deviceFeatures2 test

external/openglcts/modules/gl/gl4cGPUShaderFP64Tests.cpp
c1784ee541a30d700e7caed735353ac109d507c6 attempted to fix #51 already, but
had a few shortcommings:
1. it checked if a edge case is present by comparing the expected and the first argument
actually the actual result and the first argument have to be compared. The expected result
was always 0, so this condition was never true;
2. while iterating over the components the edge_case_present was set bac to false if the
last component wasn't an edge case
fix those issues and make drivers pass the test where floor(a/a) might return 0
=> Properly handle edge case in GL FP64 tests

external/vulkancts/modules/vulkan/conditional_rendering/vktConditionalClearAttachmentTests.cpp, external/vulkancts/modules/vulkan/conditional_rendering/vktConditionalDispatchTests.cpp, external/vulkancts/modules/vulkan/conditional_rendering/vktConditionalDrawTests.cpp, external/vulkancts/modules/vulkan/conditional_rendering/vktConditionalRenderingTestUtil.cpp, external/vulkancts/modules/vulkan/conditional_rendering/vktConditionalRenderingTestUtil.hpp
Renamed conditional rendering tests to indicate what command buffer they use.
New Tests: dEQP-VK.conditional_rendering.\*.condition_secondary_buffer\*
The changes are similar in all three test groups. 
Now all cases are covered:
- Conditional rendering in primary buffer
- Conditional rendering in primary buffer executing secondary with inherited conditional rendering
- Conditional rendering in secondary buffer **(new)**
=> Add tests of VK_EXT_conditional_rendering for secondary command buffer

external/vulkancts/modules/vulkan/wsi/vktWsiSwapchainTests.cpp
Add test for acquiring too many images via `vkAcquireNextImageKHR` with non-infinite timeout, which is technically valid.
=> Add tests of VkSwapchain acquiring too many images

external/openglcts/modules/gl/gl3cTextureSizePromotion.cpp
"OpenGL 3.1 with GL_ARB_compatibility" spec, section 3.9.12:
```
The values of DEPTH_TEXTURE_MODE, TEXTURE_COMPARE_MODE,
and TEXTURE_COMPARE_FUNC are LUMINANCE, NONE, and LEQUAL
respectively.
```
In case when OpenGL 3.1 context has GL_ARB_compatibility enabled result for texelFetch of depth texture is `(depth, depth, depth, 1)` instead of `(depth, 0, 0, 1)`. Therefore we should set GL_DEPTH_TEXTURE_MODE to GL_RED.
Change shaders' glsl version to 140 to match OpenGL 3.1
=> Fix texture_size_promotion failures with OpenGL 3.1

external/vulkancts/README.md
Unrecognized command line option
'--deqp-vk-caselist-file=/home/user/VK-GL-CTS/external/vulkancts/mustpass/master/vk-default.txt'
It should be `--deqp-caselist-file`
=> Fix a typo for Linux run of deqp-vk

external/openglcts/modules/gles31/es31cShaderAtomicCountersTests.cpp
long may not be able to fit a pointer, and C++ does not allow casting
from a pointer to a smaller int.
=> Cast pointer to deUintptr instead of long

external/openglcts/modules/common/CMakeLists.txt, external/openglcts/modules/common/glcPixelStorageModesTests.cpp, external/openglcts/modules/common/glcPixelStorageModesTests.hpp, external/openglcts/modules/gl/gl3cTestPackages.cpp, external/openglcts/modules/gl/gl4cTestPackages.cpp, external/openglcts/modules/gles31/es31cTestPackage.cpp
Pixel storage modes allow to select a subregion of data when
specifying a texture image.
For example, when specifying a 2D texture image, by setting both
`GL_UNPACK_SKIP_PIXELS` and `GL_UNPACK_SKIP_ROWS`, a subrectangle can be
selected.
This set of tests contains subcases for:
- `glTexImage2D`
- `glTexImage3D`
- `glCompressedTexImage2D`
- `glCompressedTexImage3D`
Source data is filled with black colour with a white (or different
shades of grey for each layer in case of 3D textures) subregion
somewhere within it. This subregion is then selected by setting pixel
storage modes and used as a source when specifying a texture. The
correct colour is checked in a shader.
Compressed cases use two compression formats:
- `GL_COMPRESSED_RGB_S3TC_DXT1_EXT`
- `GL_COMPRESSED_RGBA_ASTC_8x5_KHR`
Adds a …
=> Add tests for usage of pixel storage modes

external/vulkancts/modules/vulkan/wsi/vktWsiColorSpaceTests.cpp
My implicit layer caches surfaces to collections keyed by instances, so CTS was crashing because it was improperly mixing objects across instances.
This change ensures the same instance and device are used to keep the Vulkan objects within the same instance.
Fixes #218
=> Fix instance mixing in surfaceFormatRenderTest

external/openglcts/modules/common/glcNearestEdgeTests.cpp
The KHR-GL33.nearest_edge.offset_right test uses an offset of 0.499 to
avoid sampling to close to the edge for rounding issues. This means that
texture sampling requires 9 or more bits of fractional precision. But
some hardware only provides 8 bits of precision, which is what D3D12
requires.
So let's instead calculate this value a bit more carefully, as follows:
0.5 - 2^-8
Components: OpenGL
Affects tests:
KHR-GL33.nearest_edge.offset_right
Fixes: https://github.com/KhronosGroup/VK-GL-CTS/issues/225
=> Lower precision required for texture-lookups

framework/platform/surfaceless/tcuSurfacelessPlatform.cpp
We really want to have a matching config.  Otherwise we end up (for
example) picking 10_10_10_2 when reference renderer is using 5_6_5.
=> platform/surfaceless: pick config's better

modules/glshared/glsFboCompletenessTests.cpp
EXT_texture_rg is based on GLES 2.0 and allows GL_R8 and GL_RG8 to be used as texture formats.
Without this fix, GLES 2.0 drivers with EXT_texture_rg report:
Unsupported texture format * requires any of the extensions or combinations: - GLES3 compatible context
Affects:
dEQP-GLES2.functional.fbo.completeness.renderable.texture.color0.r8
dEQP-GLES2.functional.fbo.completeness.renderable.texture.color0.rg8
I noticed this while trying to enable RG texture formats for the mesa lima driver at https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8549#note_769031
=> Fix missing TEXTURE_VALID for EXT_texture_rg

external/openglcts/modules/gl/gl4cEnhancedLayoutsTests.cpp, external/openglcts/modules/gl/gl4cEnhancedLayoutsTests.hpp
Explicit location on output variables may change[1] how they are located in memory - which may affect how they are handled for transform feedback; at least this is true for Mesa drivers, and its reasonable to assume that other drivers have something similar. 
In addition, automatic calculation of xfb offsets and strides, especially with 64bit types and their alignment rules[2] - doesn't have good test coverage. 
[1] Per GL_ARB_enhanced_layouts if explicit location is set for varying, each struct member, array element and matrix row will take separate location. With GL_ARB_gpu_shader_fp64/GL_ARB_gpu_shader_int64 they may take two locations.
[2] Captured double-precision variables should be aligned to 8 bytes per GL_ARB_gpu_shader_fp64:
```
"If any variable captured in transform feedback …
```
=> Add tests for XFB output of matrices/arrays/structs with explicit location (GL_ARB_enhanced_layouts)

external/openglcts/modules/common/glcPackedDepthStencilTests.cpp
When data back from glReadPixels with arguments GL_RGBA + GL_UNSIGNED_BYTE, we use GLvoid* data to get color buffer address and then use (GLuint*) to get value color.
But the reference value colorref is generated by little-endian logic, we should convert value color to LSB order or colorref to MSB order in big-endian platform.
Fix issue: https://github.com/KhronosGroup/VK-GL-CTS/issues/252
=> Add Big-Endian support in verifyColorGradient

modules/gles31/functional/es31fProgramInterfaceQueryTests.cpp
According to the OpenGL 4.5 and Open GLES 3.2 specs these tests
aren't correct:
From Section 4.4.1 (Input Layout Qualifiers) of the GLSL 4.50 spec:
```
"For some blocks declared as arrays, the location can only be applied
at the block level: When a block is declared as an array where
additional locations are needed for each member for each block array
element, it is a compile-time error to specify locations on the block
members. That is, when locations would be under specified by applying
them on block members, they are not allowed on block members. For
arrayed interfaces (those generally having an extra level of
arrayness due to interface expansion), the outer array is stripped
before applying this rule"
```
From Section 4.4.1 (Input Layout Qualifiers) of the GLSL ES 3.20 spec
```
"If an …
```
=> Disable explicit location tests for `arrayed` block members

modules/gles2/functional/es2fFboCompletenessTests.cpp
The GL_EXT_color_buffer_half_float spec is pretty clear on requiring
this:
If OES_texture_half_float is supported, textures created with:
<internalformat> = RGBA
<format> = RGBA
<type> = HALF_FLOAT_OES
are renderable.
Affects:
dEQP-GLES2.functional.fbo.completeness.renderable.texture.color0.rgba_half_float_oes
=> Require unsized half-float textures to be renderable

framework/common/tcuTestSessionExecutor.cpp
On other platforms, the standard output mode is changed to line
buffered, but that isn't possible on Windows. To allow other tools
(such as deqp-runner) to properly parse the output even if a
crash occurs, we need to flush after printing the test case name
and result.
Fixes: #311
=> Flush stdout after printing test name and result on Windows

external/fetch_sources.py
A new version addressing a security issue has been released, and the existing URL isn't valid any more.
Update to 1.2.13 and take the chance to switch to an archive URL, that should be more stable going forward.
=> Update zlib dependency

external/openglcts/modules/gl/gl3cTestPackages.hpp
For the OGL 3.1 context, if we want to use the "core profile", we need to config the "GLX_CONTEXT_FLAGS_ARB" to " GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB".
=> Correct the OGL 3.1 core profile creation logic.

external/vulkancts/modules/vulkan/synchronization/vktSynchronizationCrossInstanceSharingTests.cpp
Looks like a copy/paste bug accidentally nested the synchronization2 skip check under an FD handle type check. That causes synchronization2 tests to run on Windows drivers (which would implement the Win32 handle types instead of the FD handle types), even if synchronization2 isn't available.
=> Fix skipping when synchronization2 is unsupported on Windows

external/openglcts/modules/common/glcFramebufferBlitTests.cpp, external/openglcts/modules/common/glcTextureLodBiasTests.cpp
These files use std::fabs() but didn't include <cmath>. This used to work due to transitive includes. But a recent libc++ removes enough transitive includes that cmath now needs an explicit include.
No behavior change.
=> Add missing cmath includes

external/vulkancts/README.md
At XDC 2025, a driver developer complained about unclear instructions to build the Vulkan CTS. They can certainly be improved, so I used [toolbox](https://github.com/containers/toolbox) to install a fresh and minimal Fedora 42 container and made sure to include every package that I needed to install to successfully build deqp-vk with minimal options.
I'm providing the improvements as a public Github PR in order to publicly leave a trace of the work and because it's documentation only.
CC @lordalcol
=> Update Vulkan CTS Linux build instructions
